/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package main;

import Gadai.Dtransaksi;
import static Gadai.Dtransaksi.pilih;
import Gadai.GadaiDAO;
import Gadai.GadaiForm;
import Nasabah.*;
import auth.Auth;
import auth.AuthDAOImp;
import auth.AuthForm;
import barang.*;
import petugas.*;
import java.awt.CardLayout;
import java.awt.Dimension;
import java.awt.Toolkit;
import java.text.SimpleDateFormat;
import java.util.Date;
import static javax.management.Query.value;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.UIManager;
import static org.omg.CORBA.ARG_IN.value;

/**
 *
 * @author Th3-TW1N5
 */
public class Menu extends javax.swing.JFrame {

    private NasabahForm nasabah;
    private PetugasForm petugas;
    private BarangForm barang;
    private GadaiForm gadai;
    private Dtransaksi dtransaksi;
    private walpaper walpaper1;
    auth.AuthDAO a = new AuthDAOImp();

    /**
     * Creates new form menu
     */
    public Menu() {

        initComponents();

        Dimension dim = Toolkit.getDefaultToolkit().getScreenSize();
        this.setSize(dim.width, dim.width);
        jtpetugas.setText(Auth.NAMA);
        jtPetugas1.setText(Auth.NAMA);
        jtpetugas2.setText(Auth.NAMA);

//       setExtendedState(JFrame.MAXIMIZED_BOTH);
        setLocationRelativeTo(null);
        desktop.setVisible(true);

        setTitle("APLIKASI PEGADAIAN");

        nasabah = new NasabahForm();
        petugas = new PetugasForm();
        barang = new BarangForm();
        gadai = new GadaiForm();
        walpaper1 = new walpaper();
        dtransaksi = new Dtransaksi();

        desktop.add("w", walpaper1);
        desktop.add("n", nasabah);
        desktop.add("p", petugas);
        desktop.add("b", barang);
        desktop.add("g", gadai);
        desktop.add("d", dtransaksi);

        desktop.setVisible(true);
    }

    private void showpanel(String panelIdentifier) {
        CardLayout cardLayout = (CardLayout) desktop.getLayout();
        cardLayout.show(desktop, panelIdentifier);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jakses = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        tfpetugas = new javax.swing.JLabel();
        jtpetugas2 = new javax.swing.JLabel();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jmaster = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        tfpetugas1 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        tfpetugas2 = new javax.swing.JLabel();
        jtPetugas1 = new javax.swing.JLabel();
        jBnasabah = new javax.swing.JButton();
        jbarang = new javax.swing.JButton();
        jpetugas = new javax.swing.JButton();
        jtransaksi = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        jtpetugas = new javax.swing.JLabel();
        jBtransaksi = new javax.swing.JButton();
        datatransaksi = new javax.swing.JButton();
        desktop = new javax.swing.JDesktopPane();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jakses.setBackground(new java.awt.Color(255, 255, 255));
        jakses.setTabLayoutPolicy(javax.swing.JTabbedPane.SCROLL_TAB_LAYOUT);
        jakses.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jakses.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N

        jPanel1.setBackground(new java.awt.Color(204, 255, 51));
        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/1493299630_profle.png"))); // NOI18N

        tfpetugas.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N

        jtpetugas2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jtpetugas2.setText("USER");

        jButton4.setFont(new java.awt.Font("Sitka Small", 1, 18)); // NOI18N
        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/Home-icon (1).png"))); // NOI18N
        jButton4.setText("Home");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jButton5.setFont(new java.awt.Font("Sitka Small", 1, 18)); // NOI18N
        jButton5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/account-logout-48.png"))); // NOI18N
        jButton5.setText("Logout");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton4)
                .addGap(18, 18, 18)
                .addComponent(jButton5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 1522, Short.MAX_VALUE)
                .addComponent(tfpetugas, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jtpetugas2)
                .addGap(10, 10, 10)
                .addComponent(jLabel8)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(9, 9, 9)
                        .addComponent(jLabel8))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton4)
                            .addComponent(jButton5)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jtpetugas2)
                            .addComponent(tfpetugas, javax.swing.GroupLayout.PREFERRED_SIZE, 11, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jakses.addTab("Akses", jPanel1);

        jmaster.setBackground(new java.awt.Color(102, 255, 0));
        jmaster.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1152, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 489, Short.MAX_VALUE)
        );

        tfpetugas1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/1493299630_profle.png"))); // NOI18N

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/1493299630_profle.png"))); // NOI18N

        jtPetugas1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jtPetugas1.setText("USER");

        jBnasabah.setFont(new java.awt.Font("Sitka Small", 1, 18)); // NOI18N
        jBnasabah.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/User-Group-icon.png"))); // NOI18N
        jBnasabah.setText("Nasabah");
        jBnasabah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBnasabahActionPerformed(evt);
            }
        });

        jbarang.setFont(new java.awt.Font("Sitka Small", 1, 18)); // NOI18N
        jbarang.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/System-Package-icon.png"))); // NOI18N
        jbarang.setText("Barang");
        jbarang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbarangActionPerformed(evt);
            }
        });

        jpetugas.setFont(new java.awt.Font("Sitka Small", 1, 18)); // NOI18N
        jpetugas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/Administrator-icon.png"))); // NOI18N
        jpetugas.setText("Petugas");
        jpetugas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jpetugasActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jmasterLayout = new javax.swing.GroupLayout(jmaster);
        jmaster.setLayout(jmasterLayout);
        jmasterLayout.setHorizontalGroup(
            jmasterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jmasterLayout.createSequentialGroup()
                .addGroup(jmasterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jmasterLayout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(tfpetugas2))
                    .addGroup(jmasterLayout.createSequentialGroup()
                        .addGap(8, 8, 8)
                        .addComponent(jBnasabah)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jbarang)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jpetugas)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jtPetugas1)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel10)
                .addContainerGap())
            .addGroup(jmasterLayout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 846, Short.MAX_VALUE))
            .addGroup(jmasterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jmasterLayout.createSequentialGroup()
                    .addGap(538, 538, 538)
                    .addComponent(tfpetugas1, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                    .addComponent(jLabel9)
                    .addContainerGap(1364, Short.MAX_VALUE)))
        );

        jmasterLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jBnasabah, jbarang, jpetugas});

        jmasterLayout.setVerticalGroup(
            jmasterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jmasterLayout.createSequentialGroup()
                .addGroup(jmasterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tfpetugas2)
                    .addGroup(jmasterLayout.createSequentialGroup()
                        .addGap(9, 9, 9)
                        .addGroup(jmasterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel10)
                            .addGroup(jmasterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jpetugas)
                                .addComponent(jbarang)
                                .addComponent(jBnasabah)
                                .addComponent(jtPetugas1)))))
                .addGap(38, 38, 38)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(jmasterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jmasterLayout.createSequentialGroup()
                    .addGap(255, 255, 255)
                    .addGroup(jmasterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel9)
                        .addGroup(jmasterLayout.createSequentialGroup()
                            .addGap(16, 16, 16)
                            .addComponent(tfpetugas1, javax.swing.GroupLayout.PREFERRED_SIZE, 11, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addContainerGap(290, Short.MAX_VALUE)))
        );

        jmasterLayout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {jBnasabah, jbarang, jpetugas});

        jakses.addTab("Master", jmaster);

        jtransaksi.setBackground(new java.awt.Color(0, 204, 51));
        jtransaksi.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/1493299630_profle.png"))); // NOI18N

        jtpetugas.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jtpetugas.setText("USER");

        jBtransaksi.setFont(new java.awt.Font("Sitka Small", 1, 18)); // NOI18N
        jBtransaksi.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/transaksi 2.png"))); // NOI18N
        jBtransaksi.setText("Transaksi");
        jBtransaksi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtransaksiActionPerformed(evt);
            }
        });

        datatransaksi.setFont(new java.awt.Font("Sitka Small", 1, 18)); // NOI18N
        datatransaksi.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/view-details-48.png"))); // NOI18N
        datatransaksi.setText("Data Transaksi");
        datatransaksi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                datatransaksiActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jtransaksiLayout = new javax.swing.GroupLayout(jtransaksi);
        jtransaksi.setLayout(jtransaksiLayout);
        jtransaksiLayout.setHorizontalGroup(
            jtransaksiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jtransaksiLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jBtransaksi)
                .addGap(18, 18, 18)
                .addComponent(datatransaksi)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 1434, Short.MAX_VALUE)
                .addComponent(jtpetugas)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel11)
                .addContainerGap())
        );
        jtransaksiLayout.setVerticalGroup(
            jtransaksiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jtransaksiLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jtransaksiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel11)
                    .addGroup(jtransaksiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jBtransaksi)
                        .addComponent(jtpetugas)
                        .addComponent(datatransaksi)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jakses.addTab("Transaksi", jtransaksi);

        desktop.setLayout(new java.awt.CardLayout());

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(desktop)
                .addContainerGap())
            .addComponent(jakses)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jakses, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(desktop, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(608, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void datatransaksiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_datatransaksiActionPerformed
        // TODO add your handling code here:

        if (Auth.HAK.equals("Kasir")) {
            Dtransaksi.hapus.setVisible(false);
            Dtransaksi.berdasarkan.setVisible(false);
            Dtransaksi.pilih.setVisible(false);
            Dtransaksi.cetak.setVisible(false);
            Dtransaksi.cetak1.setVisible(false);
            Dtransaksi.tglawal.setVisible(false);
            Dtransaksi.tglakhir.setVisible(false);
            desktop.setVisible(true);
            showpanel("d");

        } else {
            Dtransaksi.hapus.setVisible(true);
            Dtransaksi.pilih.setVisible(true);
            pilih.setSelectedIndex(0);

            desktop.setVisible(true);
            showpanel("d");
            //
        }
    }//GEN-LAST:event_datatransaksiActionPerformed

    private void jBtransaksiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtransaksiActionPerformed
        // TODO add your handling code here:

        if (Auth.HAK.equals("Kasir")) {

            GadaiForm.hapustebusan.setVisible(false);
            desktop.setVisible(true);
            showpanel("g");

        } else if (Auth.HAK.equals("Admin")) {
            GadaiForm.hapustebusan.setVisible(true);
            desktop.setVisible(true);
            showpanel("g");

        } else {
            desktop.setVisible(true);
            showpanel("g");
        }
    }//GEN-LAST:event_jBtransaksiActionPerformed

    private void jbarangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbarangActionPerformed
        // TODO add your handling code here:
        desktop.setVisible(true);
        showpanel("b");
    }//GEN-LAST:event_jbarangActionPerformed

    private void jBnasabahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBnasabahActionPerformed
        // TODO add your handling code here:
        desktop.setVisible(true);
        showpanel("n");
    }//GEN-LAST:event_jBnasabahActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:

        if ((JOptionPane.showConfirmDialog(null, " Anda Yakin Ingin Logout .." + "?", "Perhatian",
            JOptionPane.YES_NO_OPTION)) == 0) {

    new auth.AuthForm().setVisible(true);
    a.logout();

    dispose();
    }
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        desktop.setVisible(true);
        showpanel("w");
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jpetugasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jpetugasActionPerformed
        // TODO add your handling code here:
          desktop.setVisible(true);
        showpanel("p");
    }//GEN-LAST:event_jpetugasActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }

        //</editor-fold>
        //</editor-fold>
        try {
            com.jtattoo.plaf.mcwin.McWinLookAndFeel.setTheme("Large-Font", "Java Swing", "");
            UIManager.setLookAndFeel("com.jtattoo.plaf.mcwin.McWinLookAndFeel");
//                new MenuHome().setVisible(true);

        } catch (Exception ex) {
            ex.printStackTrace();
        }
//        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
//                new Menu().setVisible(true);
                Menu myFrame = new Menu();
                myFrame.setVisible(true);
                myFrame.setExtendedState(myFrame.getExtendedState() | JFrame.MAXIMIZED_BOTH);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton datatransaksi;
    private javax.swing.JDesktopPane desktop;
    private javax.swing.JButton jBnasabah;
    private javax.swing.JButton jBtransaksi;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTabbedPane jakses;
    private javax.swing.JButton jbarang;
    private javax.swing.JPanel jmaster;
    public static javax.swing.JButton jpetugas;
    private javax.swing.JLabel jtPetugas1;
    private javax.swing.JLabel jtpetugas;
    private javax.swing.JLabel jtpetugas2;
    private javax.swing.JPanel jtransaksi;
    private javax.swing.JLabel tfpetugas;
    private javax.swing.JLabel tfpetugas1;
    private javax.swing.JLabel tfpetugas2;
    // End of variables declaration//GEN-END:variables
}
